import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { PetService } from '../../services/pet.service';
import { Pet } from '../../models/pet.model';

@Component({
  selector: 'app-pet-form',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div>
      <h3>Pet Form</h3>
      <form (ngSubmit)="onSubmit()">
        <input type="text" [(ngModel)]="pet.name" name="name" placeholder="Name" required>
        <input type="number" [(ngModel)]="pet.age" name="age" placeholder="Age" required>
        <input type="number" [(ngModel)]="pet.weight" name="weight" placeholder="Weight" required>
        <button type="submit">Submit</button>
      </form>
    </div>
  `
})
export class PetFormComponent {
  pet: Pet = {
    id: 0, // ID is generated by the backend
    name: '', 
    isFavorite: false,
    category: '', // Optional, can be selected later
    age: 0, 
    weight: 0, 
    favoriteFood: '' // Optional, can be selected later
  };

  constructor(private petService: PetService) {}

  // Submit form and send pet data to the service
  onSubmit() {
    // Here, you already have the `pet` object populated with the form data
    console.log(this.pet); // You can log the pet to see the values

    // Send the pet data to the backend
    this.petService.addPet(this.pet).subscribe({
      next: (response) => {
        console.log('Pet added successfully:', response);
        // Reset form after submission
        this.pet = { id: 0, name: '', isFavorite: false, category: '', age: 0, weight: 0, favoriteFood: '' };
      },
      error: (err) => {
        console.error('Error adding pet:', err);
      }
    });
  }
}
